package Domain;

import java.util.Random;

public class PlanUserNameException extends Exception 
{
    private String userName;
    private String oldUserName;

    public PlanUserNameException(String oldUserName)
    {
       this.oldUserName = oldUserName;
       userName = generateUserName();
    }

    public String getUserName() 
    {
        return userName;
    }

    @Override
    public String toString() 
    {
        return "The username (" + oldUserName +") was not valid and a new username (" + userName + ") is generated by admin and assigned for the Plan";
    }
    
    public String generateUserName()
    {
        return "USR" + String.format("%06d", new Random().nextInt(999999)) + "U";
    }

}
