package Domain;

public class PlanException extends Exception 
{
    int ID;
    int oldID;

    public PlanException(int oldID) 
    {
        this.oldID = oldID;
        this.ID = generateID();
    }

    public int getID() 
    {
        return ID;
    }

    @Override
    public String toString() 
    {
        return "The Plan ID (" + oldID +") was not valid and a new ID (" + ID + ") is generated by admin and assigned for the Plan";
    }

    public int generateID() 
    {
        return 300000+(int) (Math.random()*100000);
    }
}